### ISSUE TITLE
Add sticky notification if websocket fails to connect

### ISSUE THREAD

**Issue by stefanv** [cesium-ml/cesium_web#132]
Otherwise nothing works, and users don't know why

**Comment by hatsy** [comment]
What should be the behavior when the socket is connected but not authenticated (ie status color orange)?

**Comment by stefanv** [comment]
I think that should be the same as disconnected.

If possible, we'd only like for these notifications to show up after three seconds or so, otherwise you'll always see the error pop up upon reload.  Do you have any ideas on how to do that?
