### ISSUE TITLE
Write up instructions for serving up Cesium with SSL

### ISSUE THREAD

**Issue by stefanv** [cesium-ml/cesium_web#145]

**Comment by cesium-sync** [comment]
➤ Stéfan van der Walt commented:
Ideally, we'd like something as simple as the instructions for Jupyter-Hub: https://github.com/jupyterhub/jupyterhub

**Comment by cesium-sync** [comment]
➤ Brunston Poon commented:
https://gist.github.com/brunston/3c5b032f7a4c4882955f1c8985ca7fb1
