### ISSUE TITLE
Investigate `celery` slowness and/or look into replacements

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium_web#47]
Since reorganizing `celery` tasks to be more easily chained/used in the web front end, performance has gotten horrible: the EEG example takes ~20s to featurize with `celery` as opposed to <1s without.

Could be:
1) Bug in `celery` involving chains/chords
2) Something inefficient about my implementation (but what really changed...?)
3) `celery` is bad and it should feel bad

**Comment by acrellin** [comment]
`celery` should feel bad about itself? :+1:
