### ISSUE TITLE
Sort prediction results by probability 

### ISSUE THREAD

**Issue by acrellin** [cesium-ml/cesium_web#48]
Display probabilistic prediction results in order of decreasing class probability. Perhaps even label first as "Top Class"

**Comment by bnaul** [comment]
I was thinking about this...but having the order the same across rows is nice too. What about just **bold**ing the highest probability + corresponding class?

**Comment by acrellin** [comment]
Yeah, that sounds good!

**Comment by acrellin** [comment]
Or change the background color of those cells - light blue highlighting?

**Comment by bnaul** [comment]
even better!

**Comment by acrellin** [comment]
Both could be best!

**Comment by bnaul** [comment]
Predictions are now sorted on the backend as of d13e55c1942aeefb92c3f257beb1da7b43d223a3, but the front-end table doesn't seem to preserve the order in which things are received.
