### ISSUE TITLE
unable to run the app on osx

### ISSUE THREAD

**Issue by geraldstanje** [cesium-ml/cesium_web#58]
Hi,

Im not sure how to start the app on osx. Could you please give some feedback/infos?
http://ideone.com/oDCNje

**Comment by stefanv** [comment]
You have two options: 1. Install all the dependencies, including postgres, and run the app natively or 2. Use the docker images provided.  I'd opt for option #2, but we are sorting out a small problem we've uncovered; we should have it fixed later today.

**Comment by geraldstanje** [comment]
great, i wait for the docker to be fixed.

here is my current docker log, i hope i started it in the right way? http://paste.ofcode.org/8aesujfwhyRQKP7XbFXMpW

**Comment by stefanv** [comment]
@geraldstanje Can you give it another go?

Please follow the instructions gives on http://cesium.ml

Thanks!
