### ISSUE TITLE
Improve features plot + add others

### ISSUE THREAD

**Issue by geraldstanje** [cesium-ml/cesium_web#60]
Hi,

i have a feature request regarding the plotting.
at the moment all features are plotted within the page:
https://s31.postimg.org/huxwtniiz/Screen_Shot_2016_07_20_at_5_47_08_PM_1.png

would it be possible to select the feature to be plotted and plot it in a separated window in order to see the data with a higher resolution and possible zoom and move?

**Comment by bnaul** [comment]
- [ ] Select features to be plotted
- [ ] Investigate alternatives to Plotly (Bokeh?)
- [ ] Raw time series plots
- [ ] Prediction plots
