### ISSUE TITLE
In Chrome, incorrect behavior after creating new project

### ISSUE THREAD

**Issue by acrellin** [cesium-ml/cesium_web#66]
![screenshot from 2016-07-27 11 10 58](https://cloud.githubusercontent.com/assets/7230285/17186644/e596b6ce-53ea-11e6-953b-e76281d7ccac.png)

The newly created project is not selected, and this message (with a square?) is displayed when it shouldn't be. 

Console shows `Uncaught TypeError: Cannot convert undefined or null to object` which is raised during `throw err;` in

```
      var nextState = state;
      var nextError = void 0;
      try {
        nextState = reducer(state, action);
      } catch (err) {
        nextError = err.toString();
        if ((typeof window === 'undefined' ? 'undefined' : _typeof(window)) === 'object' && typeof window.chrome !== 'undefined') {
          // In Chrome, rethrowing provides better source map support
          setTimeout(function () {
            throw err;
          });
        } else {
          console.error(err);
        }
      }
```

Works fine in Firefox.

**Comment by bnaul** [comment]
Can't reproduce on OS X Chrome 51...

**Comment by stefanv** [comment]
The unicode display error is interesting.  Maybe we should replace it with an image to be safe.

**Comment by bnaul** [comment]
@acrellin can I close this? assume it was fixed.

**Comment by acrellin** [comment]
This is still outstanding, though @stefanv seemed to think it is due to a Chrome bug and not our code.

**Comment by acrellin** [comment]
The arrow does correctly display now though.

**Comment by acrellin** [comment]
Closing this as it's obviously a Chrome bug. I'm only seeing this with `google-chrome-stable`, but not with either `beta` or `unstable`. Assume the fix is on the way to `stable`, too.
