### ISSUE TITLE
Always use fixture data in frontend tests

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium_web#84]
Right now, fixture data is created before each test, but it isn't necessarily selected on the front end; I think we just keep whatever the default (first) value is.

Actual example of why this is bad: a test was added that checks that a 0-feature featureset can't be created; #71 broke this, and so when running those tests that featureset gets created _and then also used for model-building tests_. So every single test after that one fails, even though actually everything is working properly. Kind of defeats the purpose of using fixture data at all.

I assume this is an easy fix but have no idea how form selections work in React...cc @acrellin .

**Comment by acrellin** [comment]
@bnaul I don't think that's what's going on. A new project is created and manually selected for each test, which wouldn't contain data from previous tests, even if they weren't destroyed. In the cannot-compute-zero-features test (or any test for that matter), if an exception occurs and the context manager's final clean-up statements don't get run, a new (clean) project is still created and selected for any subsequent tests, so I don't see how this could be happening.

**Comment by bnaul** [comment]
I can't remember exactly why this was happening anymore, but I also have pushed some changes to the context managers since: now the cleanup should happen regardless even when exceptions are raised. If I run into a similar issue again I'll re-open w/ specifics but for now let's hope it's not a problem anymore.
