### ISSUE TITLE
Document Docker build process

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium_web#96]
Could just be internally. Mostly I just don't like that I don't know how to do it 😬 .

Would it be crazy to try to automate this via Travis...?

**Comment by stefanv** [comment]
Not at all crazy!

**Comment by acrellin** [comment]
Yeah I'd like to see this done, also. :+1:

**Comment by stefanv** [comment]
https://github.com/cesium-ml/cesium_web/pull/101
