### ISSUE TITLE
Fill out high-level, descriptive documentation on website

### ISSUE THREAD

**Issue by acrellin** [cesium-ml/cesium_web#98]

**Comment by bnaul** [comment]
I'm not sure what this means and @acrellin is gone; currently it says:

"Cesium is an end-to-end machine learning platform for time-series, from calculation of features to model-building to predictions. Cesium has two main components - a Python library, and a web application platform that allows interactive exploration of machine learning pipelines. Take control over the workflow in a Python terminal or Jupyter notebook with the Cesium library, or upload your time-series files, select your machine learning model, and watch Cesium do feature extraction and evaluation right in your browser with the web application."

What else do we want to add / modify?
